language: php
sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
php:
  - 7.0
  - 7.1

matrix:
  include:
    - php: 7.0
      env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'

before_script:
  - pecl install xmldiff
  - echo "xdebug.max_nesting_level=1000" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer update $COMPOSER_FLAGS

script:
  - vendor/bin/phpunit

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
